### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by qinghew** [omriav/blended-latent-diffusion#1]
Can you provide a specific date?^_^

**Comment by YingqingHe** [comment]
same question😂

**Comment by omriav** [comment]
Hi,

The code release is dependent on the review process, which we have no control over.
So unfortunately, we have no specific date yet.

Please "watch" this repository to get notified the moment the code will be released.

**Comment by ninjasaid2k** [comment]
I have this question too.

**Comment by WASasquatch** [comment]
I think this is an abandoned project, or has been implemented elsewhere in one of the various other prompt2prompt/imagic/img2img methods that have come out that do this. Makes little sense it would take this time to "review" something.

**Comment by omriav** [comment]
Hi,
The code was just released.
Thank you for your patience and sorry for the delay.
