### ISSUE TITLE
Experiments with DeepFloyd IF?

### ISSUE THREAD

**Issue by JulianKnodt** [omriav/blended-latent-diffusion#10]
I was wondering if you found that this approach also worked with DeepFloyd IF, or is it specific to stable diffusion?

**Comment by JulianKnodt** [comment]
This is completely independent. DeepFloyd is a completely different model, and the fundamental concept is not the same.

I'm asking whether application of masking with blended latent diffusion works for non-latent diffusion models.

**Comment by omriav** [comment]
> I'm asking whether the authors found that masking with blended latent diffusion works for non-latent diffusion models.

Hi,
I did not personally test it with DeepFloyd.
However, I [previously](https://omriavrahami.com/blended-diffusion-page/) performed the masked-based blending in a pixel-based diffusion model.
So, I believe it should also work on DeepFloyd.

**Comment by WASasquatch** [comment]
> This is completely independent. DeepFloyd is a completely different model, and the fundamental concept is not the same.
> 
 

The fundamental concept, and end goal, is shared by both projects, if you read their descriptions on functionality.
