### ISSUE TITLE
hello, how to get the inpainting model?

### ISSUE THREAD

**Issue by hmmlencat** [omriav/blended-latent-diffusion#11]
hello, how to get the inpainting model?  i want to try the inpainting and outpainting function

**Comment by omriav** [comment]
Hi,

Please see the [installation guide](https://github.com/omriav/blended-latent-diffusion#installation).

**Comment by MukundVarmaT** [comment]
Hi, I wasn't able to find instructions to download the checkpoint. The file [https://ommer-lab.com/files/latent-diffusion/inpainting_big.zip](https://ommer-lab.com/files/latent-diffusion/inpainting_big.zip) does not seem to contain the checkpoint.
