### ISSUE TITLE
The link for the pretrained weight is not working

### ISSUE THREAD

**Issue by chkimmmmm** [omriav/blended-latent-diffusion#2]
Hello.

Thank you for sharing great work with community. 

I tried to download pre-trained weight but I got time-out error.

So, I tried to visit your lab website but it is also not working. 

Would you please check this issue?

Thank you.

Best,
CK

**Comment by omriav** [comment]
Hi,

You are right, sorry for that.
In the meantime - please downlowd the checkpoimt from [here](https://drive.google.com/file/d/1wcOK4co3EnbFAL6UpX1SVChMBKAzkMOx/view?usp=sharing).

Thanks for letting us know.
