### ISSUE TITLE
Scripts for SD2 and SDXL

### ISSUE THREAD

**Issue by Varghese-Kuruvilla** [omriav/blended-latent-diffusion#20]
Hi, 

Just wanted to know why the edit_image function for SD2 and SDXL are different? I was under the assumption that we are changing only the SD model and everything else remains the same. Thanks in advance!

**Comment by omriav** [comment]
Hi,

The diffusers implementation of SDXL is not backward compatible.
I.e, there was a need for changes in order to adapt our method to work on SDXL.
That being said, there are no conceptual changes between the two implementations.

Best,
Omri
