### ISSUE TITLE
Workflow for scribble editing

### ISSUE THREAD

**Issue by TiesHendrickx** [omriav/blended-latent-diffusion#3]
Hi,

I would like to use your code to make small adjustments on existing images based on a rough scetch.
The scribble functionality that is described seems to be exactly what I am looking for, but how do I use it?
If I change the original image and provide a mask, how do I make sure the inpainted colors are used and not random noise?

Kind regards,
Ties

**Comment by omriav** [comment]
Hi,

You can control the fidelity to the mask by the `--skip_steps` parameter, the more steps you skip, the more the output result will correspond to the input mask.
This is illustrated in page 30 in [Blended Diffusion paper](https://arxiv.org/pdf/2111.14818.pdf).
