### ISSUE TITLE
Some typos on Blended Latent Diffusion webpage.

### ISSUE THREAD

**Issue by 46319943** [omriav/blended-latent-diffusion#5]
It seems some typos on the project webpage, as shown in the figures below.
- ![1](https://user-images.githubusercontent.com/17161318/229336993-ad5f0f59-80ed-4d1a-aca7-1171d53efecd.jpg)
- ![2](https://user-images.githubusercontent.com/17161318/229336998-7771c378-3b48-4a98-88a8-149d9b899341.jpg)

**Comment by omriav** [comment]
Hi,

Thank you very much for reporting it!

Omri
