### ISSUE TITLE
wrong result with the demo 

### ISSUE THREAD

**Issue by dreamlychina** [omriav/blended-latent-diffusion#7]
python scripts/text_editing.py --prompt "text "ECCV"" --init_image "inputs/img.png" --mask "inputs/mask.png"
When I use your demo to generate the text "ECCV",  the "text" is also  generated in the img, which is different in your paper.  Could please tell me the reason ??? thanks a lot.

**Comment by omriav** [comment]
Hi,
In the paper I used a more elaborated text: `a children's book titled \"ECCV\"`.
Can you please try to use a more elaborated text prompt?
