### ISSUE TITLE
how to achieve the Scribble-guided editing

### ISSUE THREAD

**Issue by Mr-Bright** [omriav/blended-latent-diffusion#8]
I am very interested about the Scribble-guided editing which is posed in the paper, but I am confused how to use those code to evalutate it. Could you give me some instruction, pls?

**Comment by omriav** [comment]
Hi,

The scribble need to be done with an external image editing app.
Then you provide a mask to the scribbles area and perform the standard image editing guided by the text prompt.

One important hyperparameter is the number of denoising steps, which controls the correspondence to the input scribble. For more details see Figure 32 in [Blended Diffusion paper](https://omriavrahami.com/blended-diffusion-page/).
